from django.db import migrations, models
import django.db.models.deletion
import django.contrib.auth.models

class Migration(migrations.Migration):
    initial=True
    dependencies=[("auth","0012_alter_user_first_name_max_length")]
    operations=[
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("name",models.CharField(max_length=160)),("sku",models.CharField(max_length=80,unique=True)),
                ("product_type",models.CharField(max_length=30)),("unit",models.CharField(default="pcs",max_length=20)),
                ("minimum_stock",models.DecimalField(decimal_places=2,default=0,max_digits=14)),
                ("location",models.CharField(blank=True,max_length=120)),
                ("thickness",models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),
                ("size",models.CharField(blank=True,max_length=80)),("color",models.CharField(blank=True,max_length=80)),
                ("is_active",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),
            ]),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("role",models.CharField(default="viewer",max_length=30)),("full_name",models.CharField(blank=True,max_length=160)),
                ("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="profile",to="auth.user")),
            ]),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("quantity",models.DecimalField(decimal_places=2,default=0,max_digits=14)),
                ("average_cost",models.DecimalField(decimal_places=2,default=0,max_digits=14)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("product",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="inventory",to="erp.product")),
            ]),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("quantity_change",models.DecimalField(decimal_places=2,max_digits=14)),
                ("quantity_after",models.DecimalField(decimal_places=2,max_digits=14)),
                ("movement_type",models.CharField(default="adjustment",max_length=40)),
                ("note",models.CharField(blank=True,max_length=255)),("created_at",models.DateTimeField(auto_now_add=True)),
                ("product",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="movements",to="erp.product")),
            ]),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("order_number",models.CharField(max_length=50,unique=True)),("customer_name",models.CharField(max_length=160)),
                ("customer_email",models.EmailField(blank=True,max_length=254)),("quantity",models.DecimalField(decimal_places=2,max_digits=14)),
                ("status",models.CharField(default="pending",max_length=20)),("notes",models.TextField(blank=True)),
                ("created_at",models.DateTimeField(auto_now_add=True)),
                ("product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="orders",to="erp.product")),
            ]),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("production_number",models.CharField(max_length=50,unique=True)),("customer_name",models.CharField(blank=True,max_length=160)),
                ("quantity",models.DecimalField(decimal_places=2,max_digits=14)),("produced_quantity",models.DecimalField(decimal_places=2,default=0,max_digits=14)),
                ("status",models.CharField(default="in-progress",max_length=20)),("assigned_to",models.CharField(blank=True,max_length=160)),
                ("started_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(blank=True,null=True)),
                ("product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="production_orders",to="erp.product")),
            ]),
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("quantity_per_unit",models.DecimalField(decimal_places=4,max_digits=14)),("unit",models.CharField(default="pcs",max_length=20)),
                ("component_product",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="used_in_boms",to="erp.product")),
                ("product",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="bom_items",to="erp.product")),
            ],
            options={"constraints":[models.UniqueConstraint(fields=("product","component_product"),name="unique_bom_component")]},
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("token_hash",models.CharField(max_length=64,unique=True)),("expires_at",models.DateTimeField()),
                ("revoked",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),
                ("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="refresh_tokens",to="auth.user")),
            ]),
    ]
